language: php

php:
  - 5.6

before_script:
  - cp .env.travis .env
  - mysql -e 'create database competentiemanager;'
  - composer self-update
  - composer install --no-interaction

script:
- vendor/bin/phpunit
language: php

php:
  - 7.1

before_script:
  - cp .env.travis .env
  - mysql -e 'create database competentiemanager;'
  - composer self-update
  - composer install --no-interaction

script:
- vendor/bin/phpunit